# Generated by Django 4.2.23 on 2025-10-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('postal_address', models.TextField(verbose_name='Dirección Postal')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número Telefónico')),
                ('service_location', models.TextField(help_text='Indique los lugares donde provee servicios médicos', verbose_name='¿Dónde provee servicios?')),
                ('is_doctor', models.BooleanField(default=False, verbose_name='¿Eres médico?')),
                ('years_practicing', models.IntegerField(blank=True, help_text='Número de años ejerciendo la medicina', null=True, verbose_name='Años ejerciendo')),
                ('is_licensed', models.BooleanField(default=False, verbose_name='¿Eres colegiado?')),
                ('needs_voting_help', models.BooleanField(default=False, verbose_name='¿Necesitará ayuda con voto adelantado?')),
                ('unique_id', models.CharField(blank=True, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico (opcional)')),
            ],
            options={
                'verbose_name': 'Registro de Simpatizante',
                'verbose_name_plural': 'Registros de Simpatizantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
