# Generated by Django 4.2.23 on 2025-10-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='is_licensed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Eres colegiado?'),
        ),
    ]
