# Generated by Django 4.2.23 on 2025-10-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_registration_is_licensed'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad'),
        ),
    ]
