# Generated by Django 5.2.7 on 2025-10-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_registration_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accepts_promotions',
            field=models.BooleanField(default=False, help_text='El usuario acepta recibir comunicaciones promocionales', verbose_name='Acepta recibir promociones'),
        ),
        migrations.AddField(
            model_name='registration',
            name='accepts_terms',
            field=models.BooleanField(default=False, help_text='El usuario acepta los términos de servicio', verbose_name='Acepta términos y condiciones'),
        ),
    ]
