# Generated by Django 5.2.7 on 2025-10-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_registration_accepts_promotions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Plan para Renovar y Avanzar', max_length=200)),
                ('archivo_pdf', models.FileField(help_text='Archivo PDF del Plan Estratégico', upload_to='plan_estrategico/')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del plan')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Estratégico',
                'verbose_name_plural': 'Planes Estratégicos',
            },
        ),
    ]
