# Generated by Django 5.2.7 on 2025-10-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_planestrategico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planestrategico',
            name='titulo',
            field=models.CharField(default='Descarga el Plan de Acción!', max_length=200),
        ),
    ]
