# Generated by Django 5.2.7 on 2025-10-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_planestrategico_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='needs_voting_help',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Necesitará ayuda con voto adelantado?'),
        ),
    ]
