# Generated by Django 5.2.7 on 2025-11-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_registration_needs_voting_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='unsubscribed',
            field=models.BooleanField(default=False, help_text='Usuario se ha dado de baja de comunicaciones', verbose_name='Dado de baja'),
        ),
        migrations.AddField(
            model_name='registration',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el usuario se dio de baja', null=True, verbose_name='Fecha de baja'),
        ),
    ]
